name: Callable
on:
    workflow_call:
        inputs:
            name:
                type: string
        secrets:
            token:
                required: false

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo ${{inputs.name}}
            - name: Secret
              run: echo ${{secrets.token}}
            - name: Workflow
              run: echo ${{github.workflow}}
